app:
  env: prod

logging:
  config: classpath:log4j2-prod.xml

http.proxy:
auth:
  dir: auth
  #like 'localhost:19013/api'
  domain: replace_with_your_om_ds_server_domain_and_base_path
download.dir: download
admob:
  client_id: replace_with_your_client_id
  client_secret: replace_with_your_client_secret

spring:
  ## datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxx/open_mediation?useCursorFetch=true&characterEncoding=utf8&useSSL=true&requireSSL=false&serverTimezone=GMT
    username: xxx
    password: xxxxx
    dbcp2:
      max-total: 320
      min-idle: 5
  jdbc:
    template:
      fetch-size: 1000